#!/bin/bash
# 🎬 PolicyGuard Demo Video Recorder Script
# Run this to generate demo frames for video editing

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     PolicyGuard Demo Video Production Kit                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if running in correct directory
if [ ! -f "scripts/demo-video-production.ts" ]; then
    echo "❌ Error: Run this from hedera-apex-hackathon-2026/ directory"
    exit 1
fi

echo "📋 Demo Video Structure:"
echo ""
echo "Scene 1 (0:00-0:45): The Problem - AI + Money = Danger"
echo "Scene 2 (0:45-1:15): The Solution - PolicyGuard Overview"  
echo "Scene 3 (1:15-2:15): Demo - Auto-Approval (3 HBAR)"
echo "Scene 4 (2:15-3:45): Demo - Human Approval (50 HBAR)"
echo "Scene 5 (3:45-4:45): Demo - Multi-Sig (50 HBAR - adjusted)"
echo "Scene 6 (4:45-5:15): Audit Trail - HCS Immutable Logs"
echo "Scene 7 (5:15-5:45): Outro - Thank You & Links"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

# Run the demo with smaller amounts for Scene 5
echo "🎬 Starting Demo Production..."
echo ""
echo "⚠️  This will execute 3 real transactions on Hedera Testnet"
echo "💰 Estimated cost: ~0.1 HBAR in fees"
echo ""
read -p "Press Enter to continue or Ctrl+C to cancel..."

echo ""
echo "⏳ Running demo script..."
npx ts-node scripts/demo-video-production.ts 2>&1 | tee demo-video-output.txt

echo ""
echo "✅ Demo complete!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📁 Output files:"
echo "   • demo-video-output.txt - Full terminal output"
echo ""
echo "🎥 To create the video:"
echo ""
echo "Option 1 - Quick (Recommended):"
echo "   Use OBS Studio or QuickTime to record terminal:"
echo "   1. Open terminal full screen (black background)"
echo "   2. Run: npx ts-node scripts/demo-video-production.ts"
echo "   3. Record screen + microphone narration"
echo "   4. Add captions in iMovie/CapCut/DaVinci"
echo ""
echo "Option 2 - Advanced:"
echo "   Use asciinema + editing:"
echo "   1. Install: npm install -g asciinema"
echo "   2. Record: asciinema rec demo.cast"
echo "   3. Convert: asciinema convert demo.cast demo.gif"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📝 Narration Script (read while recording):"
echo ""
echo "[Scene 1] AI agents are powerful but dangerous."
echo "          One mistake and millions are gone."
echo "          We need human oversight."
echo ""
echo "[Scene 2] PolicyGuard Agent: AI proposes, human approves,"
echo "          Hedera executes with immutable audit."
echo ""
echo "[Scene 3] Small payment? Auto-approved if below threshold."
echo ""
echo "[Scene 4] Medium amount? Challenge created."
echo "          Human reviews and approves."
echo "          AI cannot act alone."
echo ""
echo "[Scene 5] Large amount? Multi-signature required."
echo "          CFO and CTO must both approve."
echo ""
echo "[Scene 6] Every decision logged to Hedera."
echo "          Immutable, verifiable, compliant."
echo ""
echo "[Scene 7] Safe AI. Human Control. Immutable Proof."
echo "          PolicyGuard Agent."
echo ""
